spring:
  application:
    name: coin-control
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${EXTERNAL_DB_PORT:5432}/coin
