spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: coin-control
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${EXTERNAL_DB_PORT:5432}/coin
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/CoinControl
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${EXTERNAL_DB_PORT:5432}/coin
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.security: trace
jwt:
  cookie-token-key: '{"kty": "oct", "use": "sig", 
  "k": "TQL2PC0d1oNsWZ4ptrDdqg",
  "alg": "HS256"}'
  time-to-live: 6h
